use Mix.Config

# Configure your database
config :monitor_otter, MonitorOtter.Repo,
  username: "postgres",
  password: "postgres",
  database: "monitor_otter_dev",
  hostname: "localhost",
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we use it
# with webpack to recompile .js and .css sources.
config :monitor_otter, MonitorOtterWeb.Endpoint,
  http: [port: 4000],
  debug_errors: true,
  code_reloader: true,
  check_origin: false,
  watchers: [
    node: [
      "node_modules/webpack/bin/webpack.js",
      "--mode",
      "development",
      "--watch-stdin",
      cd: Path.expand("../assets", __DIR__)
    ]
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Note that this task requires Erlang/OTP 20 or later.
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :monitor_otter, MonitorOtterWeb.Endpoint,
  live_reload: [
    patterns: [
      ~r"priv/static/.*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*(po)$",
      ~r"lib/monitor_otter_web/(live|views)/.*(ex)$",
      ~r"lib/monitor_otter_web/templates/.*(eex)$"
    ]
  ]

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

# Swoosh configuration
config :monitor_otter, MonitorOtterWeb.Mailer,
  adapter: Swoosh.Adapters.SMTP,
  relay: System.get_env("MONITOR_OTTER_SMTP_RELAY"),
  username: System.get_env("MONITOR_OTTER_SMTP_USER"),
  password: System.get_env("MONITOR_OTTER_SMTP_PASSWORD"),
  ssl: System.get_env("MONITOR_OTTER_SMTP_USE_SSL") == "true",
  tls: String.to_atom(System.get_env("MONITOR_OTTER_SMTP_USE_TLS") || "always"),
  auth: String.to_atom(System.get_env("MONITOR_OTTER_SMTP_AUTH") || "always"),
  port: String.to_integer(System.get_env("MONITOR_OTTER_SMTP_PORT") || "587"),
  from: System.get_env("MONITOR_OTTER_SMTP_FROM")
